/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package HelloWorldKt

class App {
    val greeting: String
        get() {
            return "Hello world."
        }
}

class App1 {
    val greeting: String
        get() = "Hello world."
}

fun main(args: Array<String>) {
    println(App().greeting)
}
